#ddev-generated
# Simple template to demonstrate site-metrics-github
services:
  site-metrics-github:
    container_name: ddev-${DDEV_SITENAME}-site-metrics-github
    image: ${SITE_METRICS_GITHUB_DOCKER_IMAGE:-busybox:stable}
    command: tail -f /dev/null
    restart: "no"
    # These labels ensure this service is discoverable by DDEV.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}

    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
